# app
server:
  port: ${PORT:80}

spring:
  # Profile Config
  profiles:
    active: local
  # App Config
  application:
    name: wechat

  # file Config
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # 允许bean的覆盖 默认关闭,则@FeignClient的value值必须是全局唯一  开启后可以写多个valuei昂同@FeignClient
  main:
    allow-bean-definition-overriding: true

  # 出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/



# 配置数据库
mybatis:
  basePackage: com.pingan.wechat.mapper
  xmlLocation: classpath:mapper/**/*.xml