spring:
  # DataSource StoreConfig
  datasource:
    url: jdbc:mysql://localhost:3306/mygame?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      maxActive: 1000
      initialSize: 10
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000

wechat:
  appid: wxbbd6917123bbca1b
  secret: 783e5a090751b6803cf47263d8e15417
  #获取access_token
  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
  #获取用户信息
  userInfoUrl: https://api.weixin.qq.com/sns/userinfo
  baseUrl: http://192.168.1.165/